"""rename leasehold column

Revision ID: 0cdc7a363e9b
Revises: 
Create Date: 2025-02-12 16:46:51.963100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdc7a363e9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leasehold_remaining', sa.Integer(), nullable=True))
        batch_op.drop_column('leasehold_years_remaining')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leasehold_years_remaining', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('leasehold_remaining')

    # ### end Alembic commands ###
