"""Add buyer information fields to negotiations

Revision ID: 161f37b40070
Revises: 
Create Date: 2025-04-06 19:01:06.141713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161f37b40070'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_negotiations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_move_in_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mortgage_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_negotiations', schema=None) as batch_op:
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('mortgage_status')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('preferred_move_in_date')
        batch_op.drop_column('buyer_status')

    # ### end Alembic commands ###
