"""Add transaction progress tracking

Revision ID: 4262a4e673d7
Revises: 161f37b40070
Create Date: 2025-05-25 17:22:22.651689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4262a4e673d7'
down_revision = '161f37b40070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('mortgage_decision', sa.String(length=20), nullable=True),
    sa.Column('mortgage_provider', sa.String(length=100), nullable=True),
    sa.Column('mortgage_provider_submitted', sa.Boolean(), nullable=True),
    sa.Column('onsite_visit_required', sa.String(length=10), nullable=True),
    sa.Column('mortgage_valuation_schedule_date', sa.Date(), nullable=True),
    sa.Column('mortgage_valuation_schedule_time', sa.Time(), nullable=True),
    sa.Column('mortgage_valuation_visit_completed', sa.Boolean(), nullable=True),
    sa.Column('mortgage_offer_file_url', sa.String(length=500), nullable=True),
    sa.Column('mortgage_offer_file_name', sa.String(length=255), nullable=True),
    sa.Column('property_survey_decision', sa.String(length=10), nullable=True),
    sa.Column('surveyor_name', sa.String(length=100), nullable=True),
    sa.Column('surveyor_email', sa.String(length=120), nullable=True),
    sa.Column('surveyor_phone', sa.String(length=20), nullable=True),
    sa.Column('survey_schedule_date', sa.Date(), nullable=True),
    sa.Column('survey_schedule_time', sa.Time(), nullable=True),
    sa.Column('survey_visit_completed', sa.Boolean(), nullable=True),
    sa.Column('survey_approval', sa.String(length=20), nullable=True),
    sa.Column('buyer_solicitor_name', sa.String(length=100), nullable=True),
    sa.Column('buyer_solicitor_contact', sa.String(length=120), nullable=True),
    sa.Column('seller_solicitor_name', sa.String(length=100), nullable=True),
    sa.Column('seller_solicitor_contact', sa.String(length=120), nullable=True),
    sa.Column('buyer_final_checks_confirmed', sa.Boolean(), nullable=True),
    sa.Column('seller_final_checks_confirmed', sa.Boolean(), nullable=True),
    sa.Column('buyer_exchange_contracts_confirmed', sa.Boolean(), nullable=True),
    sa.Column('seller_exchange_contracts_confirmed', sa.Boolean(), nullable=True),
    sa.Column('buyer_completion_confirmed', sa.Boolean(), nullable=True),
    sa.Column('seller_completion_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mortgage_decision IN ('mortgage', 'cash')", name='valid_mortgage_decision'),
    sa.CheckConstraint("onsite_visit_required IN ('yes', 'no')", name='valid_onsite_visit_required'),
    sa.CheckConstraint("property_survey_decision IN ('yes', 'no')", name='valid_property_survey_decision'),
    sa.CheckConstraint("survey_approval IN ('pending', 'approved', 'rejected')", name='valid_survey_approval'),
    sa.ForeignKeyConstraint(['negotiation_id'], ['property_negotiations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_progress')
    # ### end Alembic commands ###
