"""Split property into related tables

Revision ID: 9f8f99e0cd47
Revises: 
Create Date: 2025-02-16 17:27:40.951472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f8f99e0cd47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bathrooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reception_rooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('square_footage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('epc_rating', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('main_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('additional_image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('floorplan_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ownership_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('leasehold_remaining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('property_age', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('key_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('council_tax_band', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='properties_pkey')
    )
    # ### end Alembic commands ###
