name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: property_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Format code with black
      run: |
        black app/ tests/

    - name: Check if formatting created any changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code formatting created changes. Please run 'black app/ tests/' locally and commit the changes."
          git diff
          exit 1
        fi

    - name: Run tests
      env:
        SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@localhost:5432/property_db_test
      run: |
        pytest -v tests/ 